In [2]:
import numpy as np
import scipy as sp
import time

# Power Method

We've already been through all the bad cases in our labs, so I will skip this for now.

In [ ]:
def power_method(A: np.ndarray, iterations: int, x0=None) -> float:
  # random starting vector if none given
  x = np.random.randn(A.shape[1]) if x0 is None else x0
  for i in range(iterations):
    # calculate Ax/||Ax||
    x = A @ x
    x /= np.linalg.norm(x)
  # calculate the Rayleigh quotient Ax dot x / (x dot x)
  return np.dot(A @ x, x) / np.dot(x, x)

# Basic QR Algorithm

The $QR$ Algorithm works by iteration: calculate the $QR$ decomposition of a matrix, then set the next value in the sequence of matrices to $R_iQ_i$. Eventually, this will converge to an upper triangular matrix similar to the original matrix, whose diagonal entries are the eigenvalues.

In [ ]:
def basic_qr(A: np.ndarray, iterations: int) -> float:
    for i in range(iterations):
        # calculate A_i = Q_i R_i, then A_{i+1} = R_i Q_i
        Q, R = np.linalg.qr(A)
        A = R @ Q
    # return all of A, as well as diagonal entries of A
    # if A converges to triangular matrix, those are the eigenvalues
    return A, np.diag(A)


These are used to generate $QR$ examples for my presentation.

In [ ]:
def print_latex(A: np.ndarray):
    print("\\begin{bmatrix}")
    m, n = A.shape 
    for i in range(m):
        print("\t", end="")
        for j in range(n):
            print(f"{A[i, j]:.2f}", end="")
            if j != n-1:
                print(" & ", end="")
        print(" \\\\")
    print("\\end{bmatrix} \\\\")

In [7]:
def generate_example(A: np.ndarray, iterations: int, verbose=False) -> float:
    for i in range(iterations):
        Q, R = np.linalg.qr(A)

        if verbose:
            print(f"A_{i + 1} &= ")
            print_latex(A)
            print(f"Q_{i + 1} &= ")
            print_latex(Q)
            print(f"R_{i + 1} &= ")
            print_latex(R)

        A = R @ Q

        print(f"A_{i + 2} &= ")
        print_latex(A)

        if verbose:
            print("=============================")
        
    return A, np.diag(A)

In [8]:
generate_example(np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 1]
]), 10, verbose=True)

A_1 &= 
\begin{bmatrix}
	1.00 & 2.00 & 3.00 \\
	4.00 & 5.00 & 6.00 \\
	7.00 & 8.00 & 1.00 \\
\end{bmatrix} \\
Q_1 &= 
\begin{bmatrix}
	-0.12 & 0.90 & 0.41 \\
	-0.49 & 0.30 & -0.82 \\
	-0.86 & -0.30 & 0.41 \\
\end{bmatrix} \\
R_1 &= 
\begin{bmatrix}
	-8.12 & -9.60 & -4.19 \\
	0.00 & 0.90 & 4.22 \\
	0.00 & 0.00 & -3.27 \\
\end{bmatrix} \\
A_2 &= 
\begin{bmatrix}
	9.33 & -8.98 & 2.81 \\
	-4.08 & -1.00 & 0.98 \\
	2.81 & 0.98 & -1.33 \\
\end{bmatrix} \\
A_2 &= 
\begin{bmatrix}
	9.33 & -8.98 & 2.81 \\
	-4.08 & -1.00 & 0.98 \\
	2.81 & 0.98 & -1.33 \\
\end{bmatrix} \\
Q_2 &= 
\begin{bmatrix}
	-0.88 & -0.47 & 0.02 \\
	0.39 & -0.70 & 0.60 \\
	-0.27 & 0.54 & 0.80 \\
\end{bmatrix} \\
R_2 &= 
\begin{bmatrix}
	-10.57 & 7.28 & -1.75 \\
	0.00 & 5.44 & -2.73 \\
	0.00 & 0.00 & -0.42 \\
\end{bmatrix} \\
A_3 &= 
\begin{bmatrix}
	12.61 & -1.09 & 2.74 \\
	2.83 & -5.28 & 1.08 \\
	0.11 & -0.22 & -0.33 \\
\end{bmatrix} \\
A_3 &= 
\begin{bmatrix}
	12.61 & -1.09 & 2.74 \\
	2.83 & -5.28 & 1.08 \\
	0.11 & -0.22 & 

(array([[ 1.24546103e+01, -3.79020704e+00,  2.98260834e+00],
        [ 2.06055865e-03, -5.07484810e+00,  8.50149342e-01],
        [ 8.08002903e-14, -2.15804532e-10, -3.79762186e-01]]),
 array([12.45461028, -5.0748481 , -0.37976219]))

In [9]:
generate_example(np.array([
    [1, 5],
    [-1, -3]
]), 8, verbose=False)


A_2 &= 
\begin{bmatrix}
	-3.00 & -5.00 \\
	1.00 & 1.00 \\
\end{bmatrix} \\
A_3 &= 
\begin{bmatrix}
	-1.40 & 5.80 \\
	-0.20 & -0.60 \\
\end{bmatrix} \\
A_4 &= 
\begin{bmatrix}
	-0.60 & -5.80 \\
	0.20 & -1.40 \\
\end{bmatrix} \\
A_5 &= 
\begin{bmatrix}
	1.00 & 5.00 \\
	-1.00 & -3.00 \\
\end{bmatrix} \\
A_6 &= 
\begin{bmatrix}
	-3.00 & -5.00 \\
	1.00 & 1.00 \\
\end{bmatrix} \\
A_7 &= 
\begin{bmatrix}
	-1.40 & 5.80 \\
	-0.20 & -0.60 \\
\end{bmatrix} \\
A_8 &= 
\begin{bmatrix}
	-0.60 & -5.80 \\
	0.20 & -1.40 \\
\end{bmatrix} \\
A_9 &= 
\begin{bmatrix}
	1.00 & 5.00 \\
	-1.00 & -3.00 \\
\end{bmatrix} \\


(array([[ 1.,  5.],
        [-1., -3.]]),
 array([ 1., -3.]))

In [10]:
generate_example(np.array([
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0]
]), 1, verbose=True)


A_1 &= 
\begin{bmatrix}
	0.00 & 0.00 & 0.00 & 1.00 \\
	0.00 & 0.00 & 1.00 & 0.00 \\
	0.00 & 1.00 & 0.00 & 0.00 \\
	1.00 & 0.00 & 0.00 & 0.00 \\
\end{bmatrix} \\
Q_1 &= 
\begin{bmatrix}
	0.00 & 0.00 & 0.00 & -1.00 \\
	-0.00 & 0.00 & -1.00 & 0.00 \\
	-0.00 & -1.00 & 0.00 & 0.00 \\
	-1.00 & -0.00 & -0.00 & 0.00 \\
\end{bmatrix} \\
R_1 &= 
\begin{bmatrix}
	-1.00 & 0.00 & 0.00 & 0.00 \\
	0.00 & -1.00 & 0.00 & 0.00 \\
	0.00 & 0.00 & -1.00 & 0.00 \\
	0.00 & 0.00 & 0.00 & -1.00 \\
\end{bmatrix} \\
A_2 &= 
\begin{bmatrix}
	0.00 & 0.00 & 0.00 & 1.00 \\
	0.00 & 0.00 & 1.00 & 0.00 \\
	0.00 & 1.00 & 0.00 & 0.00 \\
	1.00 & 0.00 & 0.00 & 0.00 \\
\end{bmatrix} \\


(array([[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]]),
 array([0., 0., 0., 0.]))

## Good Cases

Let $\lambda(A)$ denote set of eigenvalues of the matrix $A$.

\begin{align}
    \lambda\begin{pmatrix}
        -5/2 & 11 & -5 \\
        -2 & 29/2 & -7 \\
        -4 & 26 & -25/2
    \end{pmatrix}
    &=\left\{\frac32,-\frac32,-\frac12\right\} \\
    \lambda\begin{pmatrix}
        1 & 2 & 1 \\
        3 & 6 & 3 \\
        -4 & 8 & -4
    \end{pmatrix}
    &=\left\{3, 0, 0\right\} \\
    \lambda\begin{pmatrix}15 & -4 & -3 \\ -10 & 12 & -6 \\ -20 & 4 & -2\end{pmatrix}
    &=\left\{20, 10, -5\right\}
\end{align}

Note: the $QR$ algorithm does not always fail when there are two eigenvalues of the same magnitude, such as matrix 1.

In [11]:
def test_function(A):
    print("matrix A:", A)
    print("its eigenvalues are:", np.linalg.eigvals(A))
    A, evals = basic_qr(A, 50)
    print("Basic QR Algorithm eigenvalues:", evals)
    print("Basic QR Algorithm result:")
    print(A)
    print("--------------------------------------------------")

# matrix 1
test_function([
    [-5/2, 11, -5],
    [-2, 29/2, -7],
    [-4, 26, -25/2]
])

# matrix 2
test_function([
    [1, 2, 1],
    [3, 6, 3],
    [-4, -8, -4]
])

# matrix 3
test_function([
    [15, -4, -3],
    [-10, 12, -6],
    [-20, 4, -2]
])

matrix A: [[-2.5, 11, -5], [-2, 14.5, -7], [-4, 26, -12.5]]
its eigenvalues are: [-1.5 -0.5  1.5]
Basic QR Algorithm eigenvalues: [-1.5  1.5 -0.5]
Basic QR Algorithm result:
[[-1.50000000e+00  2.59807621e+01 -2.40416306e+01]
 [ 1.63527637e-16  1.50000000e+00 -2.44948974e+00]
 [-1.64161388e-25  4.26503797e-24 -5.00000000e-01]]
--------------------------------------------------
matrix A: [[1, 2, 1], [3, 6, 3], [-4, -8, -4]]
its eigenvalues are: [ 3.00000000e+00 -5.38770185e-16 -1.24432063e-16]
Basic QR Algorithm eigenvalues: [3.00000000e+00 9.18276524e-16 0.00000000e+00]
Basic QR Algorithm result:
[[ 3.00000000e+00 -4.60000000e+00 -1.12178429e+01]
 [ 0.00000000e+00  9.18276524e-16 -9.90488636e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
--------------------------------------------------
matrix A: [[15, -4, -3], [-10, 12, -6], [-20, 4, -2]]
its eigenvalues are: [20. -5. 10.]
Basic QR Algorithm eigenvalues: [20. 10. -5.]
Basic QR Algorithm result:
[[ 2.00000000e+01 -2.82842712e

## Bad Cases

\begin{align}
    \lambda\begin{pmatrix}
        0 & 1 & 0 \\
        1 & 0 & 0 \\
        0 & 0 & 3
    \end{pmatrix}
    &=\left\{3, -1, 1\right\} \\
    \lambda\begin{pmatrix}
        0 & 1 \\
        1 & 0
    \end{pmatrix}
    &=\left\{-1, 1\right\} \\
    \lambda\begin{pmatrix}
        4/5 & -3/5 & 0 \\
        3/5 & 4/5 & 0 \\
        1 & 2 & 2
    \end{pmatrix}
    &=\left\{2, \frac{4+3i}{5}, \frac{4-3i}{5}\right\} \\
    \lambda\begin{pmatrix}
        0 & 0 & 0 & 1 \\
        0 & 0 & 1 & 0 \\
        0 & 1 & 0 & 0 \\
        1 & 0 & 0 & 0
    \end{pmatrix}
    &=\left\{1, -1, 1, -1\right\}
\end{align}
All of these matrices have something in common: they all have 2 or more eigenvalues with the same magnitude. This is the same condition that causes the power method to break down.

In [12]:
# matrix 1
test_function([
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 3]
])

# matrix 2
test_function([
    [0, 1],
    [1, 0]
])

# matrix 3
test_function([
    [4/5, -3/5, 0],
    [3/5, 4/5, 0],
    [1, 2, 2]
])

test_function([
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0]
])

matrix A: [[0, 1, 0], [1, 0, 0], [0, 0, 3]]
its eigenvalues are: [ 1. -1.  3.]
Basic QR Algorithm eigenvalues: [0. 0. 3.]
Basic QR Algorithm result:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 3.]]
--------------------------------------------------
matrix A: [[0, 1], [1, 0]]
its eigenvalues are: [ 1. -1.]
Basic QR Algorithm eigenvalues: [0. 0.]
Basic QR Algorithm result:
[[0. 1.]
 [1. 0.]]
--------------------------------------------------
matrix A: [[0.8, -0.6, 0], [0.6, 0.8, 0], [1, 2, 2]]
its eigenvalues are: [2. +0.j  0.8+0.6j 0.8-0.6j]
Basic QR Algorithm eigenvalues: [2.  0.8 0.8]
Basic QR Algorithm result:
[[ 2.00000000e+00 -6.51143711e-01 -2.13916149e+00]
 [ 7.99360578e-16  8.00000000e-01 -6.00000000e-01]
 [ 3.99680289e-16  6.00000000e-01  8.00000000e-01]]
--------------------------------------------------
matrix A: [[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]]
its eigenvalues are: [ 1. -1.  1. -1.]
Basic QR Algorithm eigenvalues: [0. 0. 0. 0.]
Basic QR Algorithm result:
[[0. 0. 

# Hessenberg QR

## Hessenberg Reduction

In [ ]:
def sgn(a: float) -> float:
    return 1 if a > 0 else (-1 if a < 0 else 0)

# implementation of Hessenberg reduction based on https://dspace.mit.edu/bitstream/handle/1721.1/75282/18-335j-fall-2006/contents/lecture-notes/lec14.pdf
def hessenberg(A: np.ndarray):
    m = A.shape[0]
    for k in range(m - 2):
        x = A[k+1:m, k]
        v = sgn(x[0]) * np.linalg.norm(x) * np.eye(x.shape[0])[:, 0] + x
        v = v / np.linalg.norm(v)
        H = np.eye(v.shape[0]) - 2 * np.outer(v, v)
        A[k+1:m, k:m] = H @ A[k+1:m, k:m]
        A[0:m, k+1:m] = A[0:m, k+1:m] @ H
    
    return A

In [ ]:
# testing the Hessenberg algorithm: it works

print(hessenberg(np.array([
    [ 1, 2, 3, 4 ],
    [ 4, 5, 6, 82 ],
    [ 7, 8, 9, 2 ],
    [ 39, 2, 1, -5 ]
], dtype=np.float32)))

print(hessenberg(np.array([
    [5, 4, 2, 0, 59],
    [12, 5, 3, 12, 6],
    [96, 4, 696, 12, 3],
    [23, 4, 1, 2, 2],
    [66, 7, 8, 22, 1]
], dtype=np.float32)))

[[ 1.0000000e+00 -4.6453681e+00  1.6772966e+00 -2.1464462e+00]
 [-3.9824615e+01  4.5592685e+00 -3.5721788e+00  2.2451904e+00]
 [-3.9874610e-09 -8.1971916e+01 -3.6688855e+00  8.1467009e+00]
 [-2.2215856e-08  3.8377016e-06 -7.7731009e+00  8.1096172e+00]]
[[ 5.0000000e+00 -3.4636917e+01  4.3539173e+01 -4.4090643e+00
   1.9651581e+01]
 [-1.1935242e+02  4.6178152e+02  3.2531458e+02  3.2864049e-01
   2.2184420e+01]
 [-1.7088419e-06  3.2449362e+02  2.4536833e+02  8.5017357e+00
  -9.6664410e+00]
 [-4.0941001e-07 -1.3756861e-06  1.0684650e+01  2.3750327e+00
  -6.1412907e+00]
 [-1.1748288e-06 -3.8752719e-06 -1.4047679e-07 -1.5735556e+00
  -5.5248995e+00]]


In [ ]:
# now we can implement a version of the basic QR algorithm that uses Hessenberg reduction first
# and then we can compare its efficiency to the basic algorithm
def hessenberg_qr(A: np.ndarray, iterations: int) -> float:
  A = hessenberg(A)
  for i in range(iterations):
    Q, R = np.linalg.qr(A)
    A = R @ Q
  return A, np.diag(A)

# Comparison Benchmarks

Please see `file.py` for the code used to generate performance information. Instead of using the Hessenberg algorithm I programmed, I will use the one built in to NumPy, as it is likely faster.