In [1]:
import numpy as np
import scipy as sp
import time
print("Numpy", np.__version__)
!python --version

Numpy 2.2.3
Python 3.13.2


# Section 1: Power Method

In [106]:
def power_method(A: np.ndarray, iterations: int, x0=None) -> float:
  x = np.random.randn(A.shape[1]) if x0 is None else x0
  for i in range(iterations):
    x = A @ x
    x /= np.linalg.norm(x)
  return np.dot(A @ x, x) / np.dot(x, x)


# Section 2: Basic QR Algorithm

In [ ]:
def basic_qr(A: np.ndarray, iterations: int) -> float:
    for i in range(iterations):
        Q, R = np.linalg.qr(A)
        A = R @ Q
    return A, np.diag(A)


These are used to generate $QR$ examples for my presentation.

In [5]:
def print_latex(A: np.ndarray):
    print("\\begin{bmatrix}")
    m, n = A.shape 
    for i in range(m):
        print("\t", end="")
        for j in range(n):
            print(f"{A[i, j]:.2f}", end="")
            if j != n-1:
                print(" & ", end="")
        print(" \\\\")
    print("\\end{bmatrix} \\\\")

In [10]:
def generate_example(A: np.ndarray, iterations: int, verbose=False) -> float:
    for i in range(iterations):
        Q, R = np.linalg.qr(A)

        if verbose:
            print(f"A_{i + 1} &= ")
            print_latex(A)
            print(f"Q_{i + 1} &= ")
            print_latex(Q)
            print(f"R_{i + 1} &= ")
            print_latex(R)

        A = R @ Q

        print(f"A_{i + 2} &= ")
        print_latex(A)

        if verbose:
            print("=============================")
        
    return A, np.diag(A)

In [11]:
generate_example(np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 1]
]), 10, verbose=True)

A_1 &= 
\begin{bmatrix}
	1.00 & 2.00 & 3.00 \\
	4.00 & 5.00 & 6.00 \\
	7.00 & 8.00 & 1.00 \\
\end{bmatrix} \\
Q_1 &= 
\begin{bmatrix}
	-0.12 & 0.90 & 0.41 \\
	-0.49 & 0.30 & -0.82 \\
	-0.86 & -0.30 & 0.41 \\
\end{bmatrix} \\
R_1 &= 
\begin{bmatrix}
	-8.12 & -9.60 & -4.19 \\
	0.00 & 0.90 & 4.22 \\
	0.00 & 0.00 & -3.27 \\
\end{bmatrix} \\
A_2 &= 
\begin{bmatrix}
	9.33 & -8.98 & 2.81 \\
	-4.08 & -1.00 & 0.98 \\
	2.81 & 0.98 & -1.33 \\
\end{bmatrix} \\
A_2 &= 
\begin{bmatrix}
	9.33 & -8.98 & 2.81 \\
	-4.08 & -1.00 & 0.98 \\
	2.81 & 0.98 & -1.33 \\
\end{bmatrix} \\
Q_2 &= 
\begin{bmatrix}
	-0.88 & -0.47 & 0.02 \\
	0.39 & -0.70 & 0.60 \\
	-0.27 & 0.54 & 0.80 \\
\end{bmatrix} \\
R_2 &= 
\begin{bmatrix}
	-10.57 & 7.28 & -1.75 \\
	0.00 & 5.44 & -2.73 \\
	0.00 & 0.00 & -0.42 \\
\end{bmatrix} \\
A_3 &= 
\begin{bmatrix}
	12.61 & -1.09 & 2.74 \\
	2.83 & -5.28 & 1.08 \\
	0.11 & -0.22 & -0.33 \\
\end{bmatrix} \\
A_3 &= 
\begin{bmatrix}
	12.61 & -1.09 & 2.74 \\
	2.83 & -5.28 & 1.08 \\
	0.11 & -0.22 & 

(array([[ 1.24546103e+01, -3.79020704e+00,  2.98260834e+00],
        [ 2.06055865e-03, -5.07484810e+00,  8.50149342e-01],
        [ 8.08002903e-14, -2.15804532e-10, -3.79762186e-01]]),
 array([12.45461028, -5.0748481 , -0.37976219]))

In [12]:
generate_example(np.array([
    [1, 5],
    [-1, -3]
]), 100, verbose=False)


A_2 &= 
\begin{bmatrix}
	-3.00 & -5.00 \\
	1.00 & 1.00 \\
\end{bmatrix} \\
A_3 &= 
\begin{bmatrix}
	-1.40 & 5.80 \\
	-0.20 & -0.60 \\
\end{bmatrix} \\
A_4 &= 
\begin{bmatrix}
	-0.60 & -5.80 \\
	0.20 & -1.40 \\
\end{bmatrix} \\
A_5 &= 
\begin{bmatrix}
	1.00 & 5.00 \\
	-1.00 & -3.00 \\
\end{bmatrix} \\
A_6 &= 
\begin{bmatrix}
	-3.00 & -5.00 \\
	1.00 & 1.00 \\
\end{bmatrix} \\
A_7 &= 
\begin{bmatrix}
	-1.40 & 5.80 \\
	-0.20 & -0.60 \\
\end{bmatrix} \\
A_8 &= 
\begin{bmatrix}
	-0.60 & -5.80 \\
	0.20 & -1.40 \\
\end{bmatrix} \\
A_9 &= 
\begin{bmatrix}
	1.00 & 5.00 \\
	-1.00 & -3.00 \\
\end{bmatrix} \\
A_10 &= 
\begin{bmatrix}
	-3.00 & -5.00 \\
	1.00 & 1.00 \\
\end{bmatrix} \\
A_11 &= 
\begin{bmatrix}
	-1.40 & 5.80 \\
	-0.20 & -0.60 \\
\end{bmatrix} \\
A_12 &= 
\begin{bmatrix}
	-0.60 & -5.80 \\
	0.20 & -1.40 \\
\end{bmatrix} \\
A_13 &= 
\begin{bmatrix}
	1.00 & 5.00 \\
	-1.00 & -3.00 \\
\end{bmatrix} \\
A_14 &= 
\begin{bmatrix}
	-3.00 & -5.00 \\
	1.00 & 1.00 \\
\end{bmatrix} \\
A_15 &= 
\begi

(array([[ 1.,  5.],
        [-1., -3.]]),
 array([ 1., -3.]))

In [14]:
generate_example(np.array([
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0]
]), 1, verbose=True)


A_1 &= 
\begin{bmatrix}
	0.00 & 0.00 & 0.00 & 1.00 \\
	0.00 & 0.00 & 1.00 & 0.00 \\
	0.00 & 1.00 & 0.00 & 0.00 \\
	1.00 & 0.00 & 0.00 & 0.00 \\
\end{bmatrix} \\
Q_1 &= 
\begin{bmatrix}
	0.00 & 0.00 & 0.00 & -1.00 \\
	-0.00 & 0.00 & -1.00 & 0.00 \\
	-0.00 & -1.00 & 0.00 & 0.00 \\
	-1.00 & -0.00 & -0.00 & 0.00 \\
\end{bmatrix} \\
R_1 &= 
\begin{bmatrix}
	-1.00 & 0.00 & 0.00 & 0.00 \\
	0.00 & -1.00 & 0.00 & 0.00 \\
	0.00 & 0.00 & -1.00 & 0.00 \\
	0.00 & 0.00 & 0.00 & -1.00 \\
\end{bmatrix} \\
A_2 &= 
\begin{bmatrix}
	0.00 & 0.00 & 0.00 & 1.00 \\
	0.00 & 0.00 & 1.00 & 0.00 \\
	0.00 & 1.00 & 0.00 & 0.00 \\
	1.00 & 0.00 & 0.00 & 0.00 \\
\end{bmatrix} \\


(array([[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]]),
 array([0., 0., 0., 0.]))

# Section 2.2: Good Cases

Let $\lambda(A)$ denote set of eigenvalues of the matrix $A$.

\begin{align}
    \lambda\begin{pmatrix}
        -5/2 & 11 & -5 \\
        -2 & 29/2 & -7 \\
        -4 & 26 & -25/2
    \end{pmatrix}
    &=\left\{\frac32,-\frac32,-\frac12\right\} \\
    \lambda\begin{pmatrix}
        1 & 2 & 1 \\
        3 & 6 & 3 \\
        -4 & 8 & -4
    \end{pmatrix}
    &=\left\{3, 0, 0\right\} \\
    \lambda\begin{pmatrix}15 & -4 & -3 \\ -10 & 12 & -6 \\ -20 & 4 & -2\end{pmatrix}
    &=\left\{20, 10, -5\right\}
\end{align}

In [34]:
def test_function(A):
    print("matrix A:", A)
    print("its eigenvalues are:", np.linalg.eigvals(A))
    A, evals = basic_qr(A, 50)
    print("Basic QR Algorithm eigenvalues:", evals)
    print("Basic QR Algorithm result:")
    print(A)
    print("--------------------------------------------------")

# matrix 1
test_function([
    [-5/2, 11, -5],
    [-2, 29/2, -7],
    [-4, 26, -25/2]
])

# matrix 2
test_function([
    [1, 2, 1],
    [3, 6, 3],
    [-4, -8, -4]
])

# matrix 3
test_function([
    [15, -4, -3],
    [-10, 12, -6],
    [-20, 4, -2]
])

matrix A: [[-2.5, 11, -5], [-2, 14.5, -7], [-4, 26, -12.5]]
its eigenvalues are: [-1.5 -0.5  1.5]
Basic QR Algorithm eigenvalues: [-1.5  1.5 -0.5]
Basic QR Algorithm result:
[[-1.50000000e+00  2.59807621e+01 -2.40416306e+01]
 [ 1.63527637e-16  1.50000000e+00 -2.44948974e+00]
 [-1.64161388e-25  4.26503797e-24 -5.00000000e-01]]
--------------------------------------------------
matrix A: [[1, 2, 1], [3, 6, 3], [-4, -8, -4]]
its eigenvalues are: [ 3.00000000e+00 -5.38770185e-16 -1.24432063e-16]
Basic QR Algorithm eigenvalues: [3.00000000e+00 9.18276524e-16 0.00000000e+00]
Basic QR Algorithm result:
[[ 3.00000000e+00 -4.60000000e+00 -1.12178429e+01]
 [ 0.00000000e+00  9.18276524e-16 -9.90488636e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
--------------------------------------------------
matrix A: [[15, -4, -3], [-10, 12, -6], [-20, 4, -2]]
its eigenvalues are: [20. -5. 10.]
Basic QR Algorithm eigenvalues: [20. 10. -5.]
Basic QR Algorithm result:
[[ 2.00000000e+01 -2.82842712e

# Section 2.3: Bad Cases

\begin{align}
    \lambda\begin{pmatrix}
        0 & 1 & 0 \\
        1 & 0 & 0 \\
        0 & 0 & 3
    \end{pmatrix}
    &=\left\{3, -1, 1\right\} \\
    \lambda\begin{pmatrix}
        0 & 1 \\
        1 & 0
    \end{pmatrix}
    &=\left\{-1, 1\right\} \\
    \lambda\begin{pmatrix}
        4/5 & -3/5 & 0 \\
        3/5 & 4/5 & 0 \\
        1 & 2 & 2
    \end{pmatrix}
    &=\left\{2, \frac{4+3i}{5}, \frac{4-3i}{5}\right\} \\
    \lambda\begin{pmatrix}
        0 & 0 & 0 & 1 \\
        0 & 0 & 1 & 0 \\
        0 & 1 & 0 & 0 \\
        1 & 0 & 0 & 0
    \end{pmatrix}
    &=\left\{1, -1, 1, -1\right\}
\end{align}

In [35]:
# matrix 1
test_function([
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 3]
])

# matrix 2
test_function([
    [0, 1],
    [1, 0]
])

# matrix 3
test_function([
    [4/5, -3/5, 0],
    [3/5, 4/5, 0],
    [1, 2, 2]
])

test_function([
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0]
])

matrix A: [[0, 1, 0], [1, 0, 0], [0, 0, 3]]
its eigenvalues are: [ 1. -1.  3.]
Basic QR Algorithm eigenvalues: [0. 0. 3.]
Basic QR Algorithm result:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 3.]]
--------------------------------------------------
matrix A: [[0, 1], [1, 0]]
its eigenvalues are: [ 1. -1.]
Basic QR Algorithm eigenvalues: [0. 0.]
Basic QR Algorithm result:
[[0. 1.]
 [1. 0.]]
--------------------------------------------------
matrix A: [[0.8, -0.6, 0], [0.6, 0.8, 0], [1, 2, 2]]
its eigenvalues are: [2. +0.j  0.8+0.6j 0.8-0.6j]
Basic QR Algorithm eigenvalues: [2.  0.8 0.8]
Basic QR Algorithm result:
[[ 2.00000000e+00 -6.51143711e-01 -2.13916149e+00]
 [ 7.99360578e-16  8.00000000e-01 -6.00000000e-01]
 [ 3.99680289e-16  6.00000000e-01  8.00000000e-01]]
--------------------------------------------------
matrix A: [[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]]
its eigenvalues are: [ 1. -1.  1. -1.]
Basic QR Algorithm eigenvalues: [0. 0. 0. 0.]
Basic QR Algorithm result:
[[0. 0. 

## Section 3.1: Hessenberg Reduction with Householder Transformations

In [42]:
def sgn(a: float) -> float:
    return 1 if a > 0 else (-1 if a < 0 else 0)

def hess(A: np.ndarray):
    m = A.shape[0]
    for k in range(m - 2):
        x = A[k+1:m, k]
        v = sgn(x[0]) * np.linalg.norm(x) * np.eye(x.shape[0])[:, 0] + x
        v = v / np.linalg.norm(v)
        H = np.eye(v.shape[0]) - 2 * np.outer(v, v)
        A[k+1:m, k:m] = H @ A[k+1:m, k:m]
        A[0:m, k+1:m] = A[0:m, k+1:m] @ H
    
    return A

hess(np.array([
    [ 1, 2, 3, 4 ],
    [ 4, 5, 6, 82 ],
    [ 7, 8, 9, 2 ],
    [ 39, 2, 1, -5 ]
]))

array([[  1,  -4,   0,  -1],
       [-39,   3,  -2,   1],
       [  0, -81,  -3,   6],
       [  0,   0,  -6,   6]])

In [137]:
tolerance = 0.01

all_times = []

# for n in range(100, 101, 10):
for n in range(10, 310, 10):
    times = []

    iterations = 10
    while len(times) < 1:
        # steps 1, 2 and 3
        A = np.random.randn(n, n)
        x0 = np.random.randn(n)
        iterations //= 2

        # calculate eigenvalues
        evals, _ = sp.linalg.eig(A)
        # calculate matrix of eigenvalues and absolute value of eigenvalues
        evals = np.array([ evals, np.abs(evals) ])
        # sort eigenvalues by absolute value of eigenvalues (2nd row)
        evals = evals[:, np.argsort(evals[1])[::-1]]
        if np.isclose(evals[1, 0], evals[1, 1]):
            continue

        while True:
            # time power method
            start = time.time()
            dominant = power_method(A, iterations, x0=x0)
            end = time.time()

            # calculate absolute value of returned thing
            abs_dominant = abs(dominant)
            abs_dominant_correct = abs(evals[0, 0])

            # check error and then add time
            # print(abs_dominant, abs_dominant_correct, abs(abs_dominant - abs_dominant_correct), end - start)
            if abs(abs_dominant - abs_dominant_correct) < tolerance:
                times.append(end - start)
                break
            if iterations >= 10000:
                times.append(-1)
                break
        
            # if error too bad add 10 to iterations
            iterations += 10

    all_times.append(times)

    average = sum(times) / len(times)
    print(f"{n}x{n}: {average * 1000}ms")

with open("result.txt", "w") as file:
    file.write(repr(all_times))

10x10: 0.5953311920166016ms
20x20: 1.277923583984375ms
30x30: 0.3483295440673828ms
40x40: 2.030611038208008ms
50x50: 2.957582473754883ms
60x60: 0.5764961242675781ms
70x70: 1.0645389556884766ms
80x80: 0.4582405090332031ms
90x90: 0.4305839538574219ms
100x100: 0.9560585021972656ms
110x110: 1.6965866088867188ms
120x120: 2.5911331176757812ms
130x130: 4.216194152832031ms
140x140: 1.016378402709961ms
150x150: 0.7071495056152344ms
160x160: 1.5916824340820312ms
170x170: 1.0919570922851562ms
180x180: 1.8208026885986328ms
190x190: 5.187749862670898ms
200x200: 1.1234283447265625ms
210x210: 2.2423267364501953ms
220x220: 1.6551017761230469ms
230x230: 15.918731689453125ms
240x240: 4.390716552734375ms
250x250: 4.629850387573242ms
260x260: 60.24670600891113ms
270x270: 61.975717544555664ms
280x280: 12.447595596313477ms
290x290: 2.6352405548095703ms
300x300: 8.119821548461914ms
